### ISSUE TITLE
Base 64 Encoding

### ISSUE THREAD

**Issue by dustinboston** [jekyll-assets/jekyll-assets#120]
It would be awesome if base64 encoding was an option so that you could inline an image or font without having to do a manual conversion. Thanks!

**Comment by ixti** [comment]
Note to myself (or anybody who is gonna jump on this):

- Provide `data_uri` filter. Example usage: `<img src="{{ asset logo.png | data_uri }}" />`
- Provide `data_uri` option (similar to autosize, but without config-wide variant - only per-tag). Example usage `{% image logo.png [data_uri] %}`
