### ISSUE TITLE
Refactor sprockets environment hookup 

### ISSUE THREAD

**Issue by ixti** [jekyll-assets/jekyll-assets#134]
- [x] Change namespace from `Jekyll::AssetsPlugin` to `Jekyll::Assets`
- [x] Need to provide configuration hook: `Jekyll::Assets.config { |assets| }`

**Comment by zmbush** [comment]
Rename resolved by #136

**Comment by ixti** [comment]
:clap:

**Comment by ixti** [comment]
Resolved in dev branch
