### ISSUE TITLE
uncss support?

### ISSUE THREAD

**Issue by tejasmanohar** [jekyll-assets/jekyll-assets#142]
Are there plans of adding `uncss` support to jekyll-assets? Basically what I mean by uncss is where unused css tags are stripped from the built code

https://github.com/giakki/uncss

**Comment by ixti** [comment]
No plans so far. As well as all 3rd-party integrations will be removed from core in future release. They will be pushed to extra gems, e.g. `jekyll-assets-autoprefixer`. So if anybody wants to jump on creation of plugin for `jekyll-assets` for uncss support I'll be happy to help, but I think source of `jekyll-assets-autoprefixer` will provide all the insights on how to write a plugin.
