### ISSUE TITLE
Add option support for filter helper

### ISSUE THREAD

**Issue by oscar811** [jekyll-assets/jekyll-assets#145]
Is there any way to support option on filter helper? I could not find any way to using image command with variable.

Example:
```
{{ some_var | image : [resize:50x50] }}
```

**Comment by ixti** [comment]
I'll take a look over a weekend.

**Comment by mykagrove** [comment]
Was there any progress on this? I've tried all kindsa things to pass a variable to image resize and output the path.
This is the closest I've got, but it just outputs the original image.
```
---
banner: test.jpg
---
{{ page.banner image [resize:30x20] | asset_path }}

**Comment by ixti** [comment]
Sorry. I forgot about this issue. I would say go with solution I have proposed here:
https://github.com/jekyll-assets/jekyll-assets/issues/162#issuecomment-115704782

```
---
banner: test.jpg
---
{{ page.banner | append:' [resize:30x20]' | image }}
```

**Comment by mykagrove** [comment]
That worked a treat, thank you very much!
