### ISSUE TITLE
Issue with asset_path

### ISSUE THREAD

**Issue by nhoizey** [jekyll-assets/jekyll-assets#146]
I try to use ```asset_path``` to get the path to a CSS.

When I put ```{% stylesheet styles %}``` in my template, I get this: ```<link rel="stylesheet" href="/assets/styles-d0760ad17e3606a0e3a0fa2395af45fc.css">```

When I put ```{% asset_path styles %}```, I get this: ```assets/posts/a-blind-legend/styles```

Why am I not getting this? ```/assets/styles-d0760ad17e3606a0e3a0fa2395af45fc.css```

The URL of my generated page is ```/2014/06/a-blind-legend.html```

**Comment by ixti** [comment]
`asset_path` is got overridden by some other plugins you use. IN your particular case it is:
https://github.com/nhoizey/nicolas-hoizey.com/blob/master/_plugins/asset_path_tag.rb

**Comment by nhoizey** [comment]
@ixti thanks! I removed it, and it works indeed.

I will have to fork it and change the name, maybe…
