### ISSUE TITLE
Issue with "-" in assets filenames?

### ISSUE THREAD

**Issue by nhoizey** [jekyll-assets/jekyll-assets#147]
I had troubles with an SCSS asset, and it took me a while to see that it may come from the filename containing a "-".

If I have a ```more-fonts.scss``` asset and I use ```{% asset_path more-fonts %}```, I get this:
```<link href="/assets/more-fonts-f3e46c15d21411fc8d5207b42790e8aa.scss" rel="stylesheet">```
(with a ```.scss``` extension)

If I rename the asset to ```morefonts.scss``` and I use ```{% asset_path morefonts %}```, I get this:
```<link href="/assets/morefonts-f3e46c15d21411fc8d5207b42790e8aa.css" rel="stylesheet">```
(with a ```.css``` extension)

**Comment by ixti** [comment]
Can't reproduce.

**Comment by ixti** [comment]
To be more "verbose":

```
./_site/2014/06/les-super-delires-des-clips-d-ok-go.html:    <link href="/assets/more-fonts-247bda8b1e9e7d97d608e495d5115803.css" rel="stylesheet">
...
./_site/404.html:    <link href="/assets/more-fonts-247bda8b1e9e7d97d608e495d5115803.css" rel="stylesheet">
./_site/404.html:var moreFontsUrl = "/assets/more-fonts-247bda8b1e9e7d97d608e495d5115803.css";
./_includes/head.html:    <link href="{% asset_path more-fonts %}" rel="stylesheet">
./_includes/foot.html:var moreFontsUrl = "{% asset_path more-fonts %}";
```
