### ISSUE TITLE
Cropping and setting JPG quality

### ISSUE THREAD

**Issue by alekseyg** [jekyll-assets/jekyll-assets#160]
In addition to resizing, cropping and setting JPG quality would be very nice to have for images. Resizing alone is seldom used in real world applications, and if you're cropping and setting quality on photos in your desktop image editor, you may as well taylor the sizes right there and then.

**Comment by abeMedia** [comment]
Couldn't agree more; cropping in particular would actually make the resize function really useful!
I found this gist which should make matters easy: https://gist.github.com/maxivak/3924976

**Comment by alekseyg** [comment]
I see in that commit `quality` was taken out of the README (I didn't see any corresponding code when I skimmed it). Will quality be implemented later?

**Comment by envygeeks** [comment]
It was an accident, now that you brought it up you reminded me that I did intend to reproxy quality.

**Comment by mykagrove** [comment]
Did cropping get added back in the end?
I've tried a few variations of 
``` {% image test.jpg [resize:100x100^ crop:100x100] %} ```
Trying to make it essentially crop zoom from any aspect ratio so the image ends up 100x100 with no stretching :)
(like background-size:cover in css)

**Comment by envygeeks** [comment]
Nobody can help you without a version, please give me a version.

**Comment by entozoon** [comment]
Ah sorry! I found a workaround in the end actually, having the image resize, then set that as a background-image and use it that way, i.e.:
```
<div style="background-image:url({% image test.jpg [resize:100x100^] | asset_path %})"></div>
```
