### ISSUE TITLE
Assets are output directly inside assets folder instead a css, js and images folder being generated

### ISSUE THREAD

**Issue by jsimplicio** [jekyll-assets/jekyll-assets#161]
I couldn't find any help online with this issue. I have my files inside javascripts, stylesheets, and images folder inside my `app/_assets`. When I build my project they are output directly inside the assets folder in `_site` and their directories (javascripts, stylesheets, images) aren't made.

**Comment by ixti** [comment]
Correct. Assets are found by their logical paths (relative to the lookup paths, `_assets/javascripts`, `_assets/stylesheets` and `_assets/images` by default) and written using logical path names with `basedir` config prefix (`assets` by default). So, with default config `_assets/stylesheets/app.css` will become `_site/assets/app.css`.

**Comment by jsimplicio** [comment]
How do I make it output inside stylesheets, javascripts, and images instead? @ixti

**Comment by ixti** [comment]
You can override configuration lookup paths:

``` yaml
# file: _config.yml
assets:
  sources:
    - _assets
```

But beware that in this case logical paths will need to include that `stylesheets` or `javascripts` part, e.g.:

``` html
{% javascript_tag javascripts/app.js %}
```

**Comment by j15e** [comment]
This is the way [Sprockets](https://github.com/sstephenson/sprockets#logical-paths) (the underlying asset manager) works with asset paths, not sure I would mess with this!

**Comment by jsimplicio** [comment]
I just prefer to have assets in their specific folders instead of them being output all together into an `assets` folder

**Comment by jsimplicio** [comment]
If I override the paths will that output them inside `styleesheets`, `javascripts`, and `images` folder inside `assets` in `_site`? @ixti

**Comment by ixti** [comment]
@jsimplicio yes.

**Comment by ixti** [comment]
Just to emphasize. Files are found by `logical path`. Logical path is a path relative to lookup path(s). Lookup paths are specified in `_config.yml` (as shown above). So if you will override `sources` config var with being just `_assets`, hierarchy of that folder will be repeated in generated one.

**Comment by jsimplicio** [comment]
Awesome. That worked!

**Comment by maxlanser** [comment]
i have project structure:
 ```
   _assets
    |__ js
    |__ images
    |__ fonts
    |__ css
   _src
    |__ _includes
    |__ _layouts
    |__ index.html
```

in **_config.yml** i specified source folder
`source: _src`

but when a run build task, assets like `css` `images` `fonts` ...   is not transferred to the destination folder 

how it make in _config.yml for that ?

many thanks))
P.S. i trying it  configurate for a few weeks along )))

**Comment by envygeeks** [comment]
```yaml
assets:
  sources:
  - ../_assets/css
  - ../_assets/img
  - ../_assets/js
```

I don't know if it'll work, but it might, if it doesn't you'll have to move `_assets` into the `_src` folder.

**Comment by maxlanser** [comment]
it is not working too(((((
but I do not want to include the `fonts` `css` folders to the `_src` folder
