### ISSUE TITLE
{%image%} tag with dynamic names.

### ISSUE THREAD

**Issue by aug-riedinger** [jekyll-assets/jekyll-assets#162]
I want to:

```
{% image {{post.image}} alt="Logo" [autosize] %}
```

It says:   

```
Liquid Exception: Couldn't find file '{{post.image}}' in _includes/resources.html, included in index.html
```

How can I do that?

**Comment by thbar** [comment]
Thanks for posting this, you made me realize it's apparently not possible to pass variables in there. In my case, I'm using an HTML include with a variable, like this:

```
{% include animation.html file="wiwrOQSsHL-account-edit-tags.gif" %}
```

But I was not able to use the file parameter from inside my include like I expected (so what's below doesn't work currently):

```
{% image {{include.file}} %}
```

This will raise "Couln't find file {{include.file}}". But then I searched and found a work around, by using the filter and capturing its output, like this:

```html
<div class="animation">
  {% capture path %}{{ include.file | asset_path }}{% endcapture %}
  <img src="{{ path }}" class="img-responsive"></img>
</div>
```

I wonder if variables interpolation is available at all here, at first sight it looks like no?

**Comment by ixti** [comment]
Variable interpolation does not work with Liquid tags. It's limitation of Liquid template engine unfortunately. So the easiest way is to use filters. In the example @thbar provided capture is not needed actually. It can be simplified to:

``` html
<div class="animation">
  <img src="{{ include.file | asset_path }}" class="img-responsive"></img>
</div>
```

But as per @aug-riedinger example, he wants to uitilize `image` helper to use autosize feature. Using filters it will be a bit tricky but possible:

``` html
{{ post.image | append:' alt="Logo" [autosize] ' | image }}
```

**Comment by aug-riedinger** [comment]
Nice answer @ixti . I thought of using the `| image` filter, but did not know about the `append:` hence did not consider it as an option (since without `[autosize]` the `<img>` is way enough).

**Comment by thbar** [comment]
@ixti thanks a ton, that will be useful. :+1:

**Comment by ixti** [comment]
I guess it can be closed now ;))

**Comment by amw** [comment]
Just a heads up that none of these solutions work with the 2.0 betas. `asset_path` and `image` no longer work as Liquid filters (you can't pipe strings into them).

**Comment by thbar** [comment]
@amw thanks for the heads up! Appreciated.

**Comment by envygeeks** [comment]
@amw @thbar that's true for now, it won't be true soon.  Lets refrain from speculation as 2.0 isn't even in beta, it's barely in alpha and still requires major feature backporting on some features.

**Comment by thbar** [comment]
@envygeeks sure - I didn't thought this would mean that the behavior would remain the same with final version, no problem. Just taking this into account should I upgrade to beta. Keep up the good work, and thanks for clarifying :-)

**Comment by amw** [comment]
@thbar Exactly what I meant.

@envygeeks I implemented my own workaround, but I'm not sending any pull requests yet. I'll sit on it for a bit and see what direction you're taking.

**Comment by envygeeks** [comment]
@amw @thbar I guess you guys will find out today because I plan on working on it a bit today after I backport a few Atom features into our Atom themes so you should see within a few hours what direction I plan to go, but more than likely I'll just copy @ixti's helpers and modify them, the baseurl problem will be included in that since that's a simple fix.  Good thing I passed the instance around everywhere even though I never used it that much outside of the base instance.

**Comment by ChrisEstanol** [comment]
I am facing similar issue as I want to dynamically populate one or two image for each of my posts

```
---
header-img: "drjekyll.jpg"
---

{{% images {{post.header-img }} %}
```

@amw @thbar any chance of sharing the workaround while waiting for the pull request.
Thanks.

**Comment by amw** [comment]
Oh, it's been fixed already. Use it old style:

```
{{ path_var | image }}
```

**Comment by ChrisEstanol** [comment]
for some reasons when I do:
```
<img src="{{ post.web-img | image }}" alt="{{ post.title}}">
```
It shows the following error
```
 Liquid Exception: Couldn't find file 'assets/images/drjekyll.jpg' in work.html
jekyll 2.5.3 | Error:  Couldn't find file 'assets/images/drjekyll.jpg'
```
Is it fixed on the beta release v2?

**Comment by amw** [comment]
It works in v2 betas. Try using master branch. Also, you're using `image` output for `src` attribute. I think you want `asset_path` then.

**Comment by envygeeks** [comment]
It need be noted that Beta only works on Jekyll 3.0 and it looks like you are using 2.5.3, we have no plans to support 2.5.3 in Jekyll Assets beta or 2.0.0 when it's finally pushed out tomorrow... because it does not support some of the features we rely on.
