### ISSUE TITLE
Don't pack and uglify in dev

### ISSUE THREAD

**Issue by aug-riedinger** [jekyll-assets/jekyll-assets#163]
Rails handles assets very well in the sense that it does pack and uglify assets, but only in production environment.

In dev, all the files are served separatelly and unchanged, which makes front-end debugging much easier.

Is there a way to achieve this configuration with Jekyll-assets?

Super nice gem by the way.

Thanks

**Comment by ixti** [comment]
Put following settings into your `_config.yml`. 

``` yaml
assets:
  js_compressor: ~
  css_compressor: ~
  debug: true
```

**Comment by ixti** [comment]
switching configs is a bit out of scope of this gem. although i will need to check new jekyll's api - probably i will be able to come with more elegant solution :D

**Comment by j15e** [comment]
@aug-riedinger I am using this hook :

```ruby
Jekyll::Hooks.register :site, :pre_render do |site|
  if Jekyll.env == 'development'
    site.assets_config.cachebust = :none
    site.assets_config.js_compressor = nil
    site.assets_config.css_compressor = nil
  end
end
```

And building in production with an env flag `JEKYLL_ENV=production bundle exec jekyll build`

**Comment by envygeeks** [comment]
This is supported in the upcoming jekyll-assets for Jekyll3, it'll be merged in sometime this week.

**Comment by aug-riedinger** [comment]
:+1: !
