### ISSUE TITLE
Merging jekyll3-assets into jekyll-assets.

### ISSUE THREAD

**Issue by envygeeks** [jekyll-assets/jekyll-assets#164]
Last night I handed over the source to jekyll-assets of jekyll3-assets so I was wondering how you wanted to handle the merger (or if you want to merge?)

Here are a few notes also:

* Jekyll3-Assets has support for autoprefixer-rails if you have JavaScript available.
* Jekyll3-Assets has built-in support for transpiling if you have JavaScript available.

Either way, after handing it over I was wondering what you guy would like to do from here on out.

**Comment by ixti** [comment]
Well. I prefer living on a bleeding edge (debian testing/sid) ;)) So, I'm totally fine to drop Jekyll `< 3.0` support. In other words :+1: from me for the merge :D

**Comment by envygeeks** [comment]
I forgot to mention that this new version is an entire rewrite, so I should mention that just incase it might change your mind, it does try and maintain the same configuration (it is still missing a few things I need to merge in) but yeah it's an entire rewrite from scratch.
