### ISSUE TITLE
use image tag without the alt attribute

### ISSUE THREAD

**Issue by cristianogregnanin** [jekyll-assets/jekyll-assets#166]
When I use the image tag like this: 
```{% image ror.jpg %}```
  
The ```alt``` attribute is not produced and I must write:
```{% image ror.jpg alt="ror" %}```

Is possibile to avoid writing the alt attribute like Ruby on Rails?

**Comment by envygeeks** [comment]
Which version are you using?

**Comment by cristianogregnanin** [comment]
1.0.0

**Comment by envygeeks** [comment]
This probably won't get fixed in 1.0.0 unless @ixti wants to fix it but in 2.0.0 we can generate the alt from the name easily enough.

**Comment by envygeeks** [comment]
Worry not, 2.0.0 is due soon, like this week or next week soon (in it's first alpha at least.)

**Comment by cristianogregnanin** [comment]
Ok thanks

**Comment by ixti** [comment]
> unless @ixti wants to fix it

I see no point in supporting 1.x - better to add backward compatibility to 2.x than trying to support outdated code.

**Comment by cristianogregnanin** [comment]
2.x is under development?

**Comment by envygeeks** [comment]
@cristianogregnanin yessum, we branched off and merged the other day, current master is the 2.x working tree... it still lacks some off the stuff from 1.x (like image resizing -- which I'll be releasing today or tomorrow) and it still lacks an upgrade guide (which will come just before the alpha -- but maybe I should release it early?)

**Comment by cristianogregnanin** [comment]
Ok thank you very much
