### ISSUE TITLE
Image alt and resize confusion

### ISSUE THREAD

**Issue by mykagrove** [jekyll-assets/jekyll-assets#169]
Hi, I know there is a newer version on it's way but thought it worth pointing out that if you have
```
{% image test.jpg [resize:25%] alt="Test bro" %}
```
It doesn't work, there is no error but the image tag outputs as HTML instead.

However this way round works fine
```
{% image test.jpg alt="Test bro" [resize:25%] %}
```

Took me a little while to figure out! Might be worth adding a note to the readme or whatever?

**Comment by envygeeks** [comment]
Can you provide examples of the output so I can see exactly what's going on to document the behavior in legacy `jekyll-assets` thanks.

**Comment by mykagrove** [comment]
Sure, running jekyll build --trace has no unusual output in either case, just a typical ```...done```.
The HTML generated however for the first case is:
```
&lt;img src=”/assets/test-af652e65abac78954ec0dc1e16f4fb3a.jpg” [resize:50x50] alt=”Test bro”&gt;
```
(with the html_entities actually like that)
And the image file generated in _site/assets is just the original file.

Hope that helps!

**Comment by ixti** [comment]
Tags and filters expect options to come at the very end. So the syntax is:

    {TAG NAME} {ASSET PATH} {HTML ATTRIBUTES}* {OPTIONS}*

**Comment by mykagrove** [comment]
^ stick that in the readme; job's a good 'un :)
