### ISSUE TITLE
Image resize does not work when used in a Liquid filter tag

### ISSUE THREAD

**Issue by knice** [jekyll-assets/jekyll-assets#171]
If I have an `image` element in the yaml front matter of a post, this works just fine: `{{ post.image | image }}`

But I can't use the `resize` attribute. Neither of the following filters work:

- `{{ post.image | image [resize:120x120] }}`
- `{{ post.image | image:resize:120x120 }}`

I get this error: `Liquid Exception: wrong number of arguments (2 for 1) in index.html`

Am I missing something?

**Comment by envygeeks** [comment]
What version are you using?

**Comment by knice** [comment]
My Gemfile.lock says: `jekyll-assets (1.0.0)`

**Comment by knice** [comment]
Thank you! And thank you for responding so quickly. I'm sorry I wasn't able to find that solution on my own.
