### ISSUE TITLE
Using variables is no longer possible

### ISSUE THREAD

**Issue by alekseyg** [jekyll-assets/jekyll-assets#173]
It is no longer possible to pipe variables to the `image` tag as described in #62 

I have a site I am making for a musician. He has a bunch of albums that I have in a collection. Albums have cover art that I would like to display.

```
{% for album in site.albums %}
  {{ album.cover | image }}
{% endfor %}
```

This used to work in Jekyll-assets 1.0, but now it will simply return the text contained in the `album.cover` variable without running it through the image tag. How can we use variables in Jekyll-assets 2.0?

**Comment by envygeeks** [comment]
Going to close this in favor of #165.  The beta currently doesn't have filters but it will once I have time to prepare for the final release coming with Jekyll 3.  It shouldn't be too long but I'm splitting my time across several projects right to prepare.
