### ISSUE TITLE
jekyll-assets and font awesome

### ISSUE THREAD

**Issue by ShootingStarr** [jekyll-assets/jekyll-assets#174]
I have this in my jekyll plugin file:
```
require "jekyll-assets"
require "jekyll-assets/font-awesome"
```

for v0.14 it's working, but when i updated to v1.0, i get this:
```
`require': cannot load such file -- jekyll-assets/font-awesome (LoadError)
```

**Comment by jroliveira** [comment]
I have the same problem.

**Comment by envygeeks** [comment]
It seems that was removed by @ixti a while back and as it was pre 1.0 I'm not inclined to put it back.

**Comment by ixti** [comment]
Yeah, that was removed as with 1.0 i wanted to get rid of all built-in plugins in favor of gemified versions but never had time to finish that...

**Comment by ixti** [comment]
I will try to introduce appropriate gem for fontawesome during this weekend.

**Comment by cressie176** [comment]
I get the same problem with bourbon

```
`require': cannot load such file -- jekyll-assets/bourbon (LoadError)
```

I'm still finding my way with Jekyll. Is there a workaround?

**Comment by ShootingStarr** [comment]
@cressie176 workaround: use v.0.14

**Comment by rrshaban** [comment]
+1

**Comment by envygeeks** [comment]
Fixed with https://github.com/jekyll-assets/jekyll-assets/commit/fad6faeb935a364afbc46a525df558489046ec5f
