### ISSUE TITLE
Getting following error while pushing a commit on GitHub. Any resolution?

### ISSUE THREAD

**Issue by ermauliks** [jekyll-assets/jekyll-assets#176]
<img width="777" alt="screen shot 2015-09-24 at 10 16 54 pm" src="https://cloud.githubusercontent.com/assets/3040988/10081221/8329a4ee-6311-11e5-9b96-7a9ff3fc0d15.png">

**Comment by envygeeks** [comment]
If you are using jekyll-assets you need to disable Jekyll on Github Pages (this is really optional but it can be done with `.nojekyll`,) build the Jekyll site locally and push up _site/*.  Github pages does not include jekyll-assets and we've not tried to get it included yet because 2.0 is not finished.

**Comment by ermauliks** [comment]
@envygeeks so I do have to add `.nojekyll` file under root?

**Comment by envygeeks** [comment]
Yes, if you put it into your Jekyll root it should land in `_site` and be pushed up with `_site`

**Comment by ermauliks** [comment]
In this case, will I've to remove `_site` folder from my `.gitignore'? Just confirming.

**Comment by envygeeks** [comment]
The _site folder should be the repo.

**Comment by ermauliks** [comment]
Sorry. I'm new to this. Currently, my Jekyll site points to master and it was working nicely till I added jekyll-assets plug-in. So, you're saying I won't be using entire jekyll code/repo anymore, I need to just upload generated `_site` folder and that will be my master. Jekyll code won't go up. Is it?

**Comment by envygeeks** [comment]
Yes that's what must happen if you use jekyll-assets because Github does not allow variables.

**Comment by envygeeks** [comment]
Sorry, I mean plugins.
