### ISSUE TITLE
Dev/Production mode

### ISSUE THREAD

**Issue by NV** [jekyll-assets/jekyll-assets#46]
I want to compile Sass with source-maps for development mode and with `--output-style=compact` for production. Any examples of how to do it with jekyll-assets?

**Comment by envygeeks** [comment]
The "compact" portion is already solved, we compress automatically in production with the option to force that compression in development.  I'm closing out this ticket (the source map part) in favor of the more direct ticket about it: https://github.com/jekyll-assets/jekyll-assets/issues/151
