### ISSUE TITLE
Problem when enabling SaSS line_comments

### ISSUE THREAD

**Issue by kurtsson** [jekyll-assets/jekyll-assets#49]
When configuring Sprockets::Sass to add line comments in the generated .css file, the asset_path function breaks.

Adding a plugin like this:

```ruby
require "sprockets/sass"
Sprockets::Sass.options[:line_comments] = true
````
works fine and comments like:
```css
/* line 250, /_assets/stylesheets/foundation/components/_orbit.scss */
```
is added in the generated CSS file which makes it much easier to track when developing.

However no 
```sass
asset_path( *path* ) 
```
is translated so the page is completely without assets. I reckon this might be a quite easy fix or perhaps adding an 
```ruby
assets:
  line_comments: true
```
would be even better!

(If I knew how to do it I would already given you a fork)

**Comment by envygeeks** [comment]
Closing this in favor of #46.
