### ISSUE TITLE
bootstrap-sass glyphicons not being brought into assets destination

### ISSUE THREAD

**Issue by delputnam** [jekyll-assets/jekyll-assets#86]
When using the built-in support for bootstrap-sass, the javascript and styles are correctly brought into the assets destination directory, but the glyphicons are not copied over.  I'm not sure if this is related to issue #85 or not.

**Comment by anroots** [comment]
A similar problem occurs with Font Awesome: the CSS file is correctly copied (when `//= require`-ing it), but the web font files are not. I've soured the web on how to 'correctly' solve this (a lib requires additional files, not only the main js or css), but have found no working solution. Sprockets has a `//= provide` directive, but this does not work here.

Any ideas, help?

**Comment by anroots** [comment]
Update: @AJ-Acevedo's solution worked. [Manually referencing](https://github.com/AJAlabs/jekyllkb/blob/master/_assets/stylesheets/jekyllkb.scss#L15) to the font files from included CSS did the trick: the font files were copied over into the `_site/assets` directory.

**Comment by rzane** [comment]
Assuming you're using bootstrap-sass, you just do the following:

```scss
@import 'bootstrap-sprockets';
@import 'bootstrap';
```

This forces bootstrap to use `font-path` to load fonts, which makes Jekyll assets load the fonts.

**Comment by envygeeks** [comment]
Closing this then, this is an upstream issue.
